<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
			<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|palette|graphics|sound|controls|keyboard|mouse|microphone|camera|disk|printer|lan|wan|timing) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.196 (unknown)" debug="no" mameconfig="10">
	<machine name="pengo" sourcefile="pengo.cpp">
		<description>Pengo (set 1 rev c)</description>
		<year>1982</year>
		<manufacturer>Sega</manufacturer>
		<rom name="ep1689c.8" size="4096" crc="f37066a8" sha1="0930de17a763a527057f60783a92662b09554426" region="maincpu" offset="0"/>
		<rom name="ep1690b.7" size="4096" crc="baf48143" sha1="4c97529e61eeca5d94938b1dfbeac41bf8cbaf7d" region="maincpu" offset="1000"/>
		<rom name="ep1691b.15" size="4096" crc="adf0eba0" sha1="c8949fbdbfe5023ee17a789ef60205e834a76c81" region="maincpu" offset="2000"/>
		<rom name="ep1692b.14" size="4096" crc="a086d60f" sha1="7079769d14dfe3873ffe29623ba0a93413706c6d" region="maincpu" offset="3000"/>
		<rom name="ep1693b.21" size="4096" crc="b72084ec" sha1="c0508951c2ad8dc31481be8b3bfee2063e3fb0d7" region="maincpu" offset="4000"/>
		<rom name="ep1694b.20" size="4096" crc="94194a89" sha1="7b47aec61593efd758e2a031f72a854bb0ba8af1" region="maincpu" offset="5000"/>
		<rom name="ep5118b.32" size="4096" crc="af7b12c4" sha1="207ed466546f40ca60a38031b83aef61446902e2" region="maincpu" offset="6000"/>
		<rom name="ep5119c.31" size="4096" crc="933950fe" sha1="fec7236b3dee2ea6e39c68440a6d2d9e3f72675a" region="maincpu" offset="7000"/>
		<rom name="ep1640.92" size="8192" crc="d7eec6cd" sha1="e542bcc28f292be9a0a29d949de726e0b55e654a" region="gfx1" offset="0"/>
		<rom name="ep1695.105" size="8192" crc="5bfd26e9" sha1="bdec535e486b43a8f5550334beff423eeace10b2" region="gfx1" offset="1000"/>
		<rom name="pr1633.78" size="32" crc="3a5844ec" sha1="680eab0e1204c9b74adc11588461651b474021bb" region="proms" offset="0"/>
		<rom name="pr1634.88" size="1024" crc="766b139b" sha1="3fcd66610fcaee814953a115bf5e04788923181f" region="proms" offset="20"/>
		<rom name="pr1635.51" size="256" crc="c29dea27" sha1="563c9770028fe39188e62630711589d6ed242a66" region="namco" offset="0"/>
		<rom name="pr1636.70" size="256" crc="77245b66" sha1="0c4d0bee858b97632411c440bea6948a74759746" region="namco" offset="100"/>
		<device_ref name="sega_315_5010"/>
		<device_ref name="ls259"/>
		<device_ref name="watchdog"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="screen"/>
		<device_ref name="speaker"/>
		<device_ref name="namco"/>
		<chip type="cpu" tag="maincpu" name="Sega 315-5010" clock="3072000"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="namco" name="Namco" clock="96000"/>
		<display tag="screen" type="raster" rotate="90" width="288" height="224" refresh="60.606061" pixclock="6144000" htotal="384" hbend="0" hbstart="288" vtotal="264" vbend="0" vbstart="224" />
		<sound channels="1"/>
		<input players="2" coins="3" service="yes">
			<control type="joy" player="1" buttons="1" ways="4"/>
			<control type="joy" player="2" buttons="1" ways="4"/>
		</input>
		<dipswitch name="Bonus Life" tag="DSW0" mask="1">
			<diplocation name="SW1" number="1"/>
			<dipvalue name="30000" value="0" default="yes"/>
			<dipvalue name="50000" value="1"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSW0" mask="2">
			<diplocation name="SW1" number="2"/>
			<dipvalue name="Off" value="2"/>
			<dipvalue name="On" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="DSW0" mask="4">
			<diplocation name="SW1" number="3"/>
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="4"/>
		</dipswitch>
		<dipswitch name="Lives" tag="DSW0" mask="24">
			<diplocation name="SW1" number="4"/>
			<diplocation name="SW1" number="5"/>
			<dipvalue name="2" value="24"/>
			<dipvalue name="3" value="16" default="yes"/>
			<dipvalue name="4" value="8"/>
			<dipvalue name="5" value="0"/>
		</dipswitch>
		<dipswitch name="Rack Test (Cheat)" tag="DSW0" mask="32">
			<diplocation name="SW1" number="6"/>
			<dipvalue name="Off" value="32" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSW0" mask="192">
			<diplocation name="SW1" number="7"/>
			<diplocation name="SW1" number="8"/>
			<dipvalue name="Easy" value="192"/>
			<dipvalue name="Medium" value="128" default="yes"/>
			<dipvalue name="Hard" value="64"/>
			<dipvalue name="Hardest" value="0"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSW1" mask="15">
			<diplocation name="SW2" number="1"/>
			<diplocation name="SW2" number="2"/>
			<diplocation name="SW2" number="3"/>
			<diplocation name="SW2" number="4"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="8"/>
			<dipvalue name="2 Coins/1 Credit" value="4"/>
			<dipvalue name="2 Coins/1 Credit 5/3" value="9"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="5"/>
			<dipvalue name="1 Coin/1 Credit" value="12" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="13"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="3"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="11"/>
			<dipvalue name="1 Coin/2 Credits" value="2"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="7"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="15"/>
			<dipvalue name="1 Coin/3 Credits" value="10"/>
			<dipvalue name="1 Coin/4 Credits" value="6"/>
			<dipvalue name="1 Coin/5 Credits" value="14"/>
			<dipvalue name="1 Coin/6 Credits" value="1"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSW1" mask="240">
			<diplocation name="SW2" number="5"/>
			<diplocation name="SW2" number="6"/>
			<diplocation name="SW2" number="7"/>
			<diplocation name="SW2" number="8"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="128"/>
			<dipvalue name="2 Coins/1 Credit" value="64"/>
			<dipvalue name="2 Coins/1 Credit 5/3" value="144"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="80"/>
			<dipvalue name="1 Coin/1 Credit" value="192" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="208"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="48"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="176"/>
			<dipvalue name="1 Coin/2 Credits" value="32"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="112"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="240"/>
			<dipvalue name="1 Coin/3 Credits" value="160"/>
			<dipvalue name="1 Coin/4 Credits" value="96"/>
			<dipvalue name="1 Coin/5 Credits" value="224"/>
			<dipvalue name="1 Coin/6 Credits" value="16"/>
		</dipswitch>
		<port tag=":DSW0">
		</port>
		<port tag=":DSW1">
		</port>
		<port tag=":IN0">
		</port>
		<port tag=":IN1">
		</port>
		<driver status="good" emulation="good" savestate="supported"/>
	</machine>
</mame>
